new Crawler({
    appId: '6GGICLXK18',
    apiKey: 'f3f92f267104875d2eaaa62dcda5ebb4',
    startUrls: ['https://wiki.meosis.fr/'],
    sitemaps: ['https://wiki.meosis.fr/sitemap.xml'],
    actions: [
      {
        indexName: 'meosis',
        pathsToMatch: ['https://wiki.meosis.fr/**'],
        recordExtractor: ({ helpers }) => {
          return helpers.docsearch({
            recordProps: {
              lvl0: {
                selectors: '',
                defaultValue: 'Documentation',
              },
              lvl1: ['header h1', 'article h1', 'main h1', 'h1', 'head > title'],
              lvl2: ['article h2', 'main h2', 'h2'],
              lvl3: ['article h3', 'main h3', 'h3'],
              lvl4: ['article h4', 'main h4', 'h4'],
              lvl5: ['article h5', 'main h5', 'h5'],
              lvl6: ['article h6', 'main h6', 'h6'],
              content: ['article p, article li', 'main p, main li', 'p, li'],
            },
            aggregateContent: true,
            recordVersion: 'v3',
          });
        },
      },
    ],
    initialIndexSettings: {
      YOUR_INDEX_NAME: {
        attributesForFaceting: ['type', 'lang'],
        attributesToRetrieve: [
          'hierarchy',
          'content',
          'anchor',
          'url',
          'url_without_anchor',
          'type',
        ],
        attributesToHighlight: ['hierarchy', 'content'],
        attributesToSnippet: ['content:10'],
        camelCaseAttributes: ['hierarchy', 'content'],
        searchableAttributes: [
          'unordered(hierarchy.lvl0)',
          'unordered(hierarchy.lvl1)',
          'unordered(hierarchy.lvl2)',
          'unordered(hierarchy.lvl3)',
          'unordered(hierarchy.lvl4)',
          'unordered(hierarchy.lvl5)',
          'unordered(hierarchy.lvl6)',
          'content',
        ],
        distinct: true,
        attributeForDistinct: 'url',
        customRanking: [
          'desc(weight.pageRank)',
          'desc(weight.level)',
          'asc(weight.position)',
        ],
        ranking: [
          'words',
          'filters',
          'typo',
          'attribute',
          'proximity',
          'exact',
          'custom',
        ],
        highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
        highlightPostTag: '</span>',
        minWordSizefor1Typo: 3,
        minWordSizefor2Typos: 7,
        allowTyposOnNumericTokens: false,
        minProximity: 1,
        ignorePlurals: true,
        advancedSyntax: true,
        attributeCriteriaComputedByMinProximity: true,
        removeWordsIfNoResults: 'allOptional',
        separatorsToIndex: '_',
      },
    },
  });